import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {Toaster} from "react-hot-toast";
import "./globals.css";
import {SupabaseProvider} from "@/lib/supabase/provider";

const geistSans = Geist({
    variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "whatcha-doin", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (<html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable}`}
        >
        <body className="antialiased">
        <Toaster/>
        <SupabaseProvider>{children}</SupabaseProvider>
        </body>
        </html>);
}
